apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx-deploy
    tier: frontend
spec:
  replicas: 2
  template:
    metadata:
      name: myapp-pod
      labels:
        app: mynginx
    spec:
      containers:
        - name: nginx
          image: nginx
  selector:
    matchLabels:
      app: mynginx