apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-kibria-nginx
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: nginx
      tire: frontend
      type: webserver
  replicas: 3
  template:
    metadata:
      name: kibria-nginx-pod
      labels:
        app: nginx 
        tire: frontend
        type: webserver
    spec:
      containers:
        - name: nginx
          image: nginx